
export const ENDPOINTS = {
    category:{
        base:'/Category',
        add:'',
        getAll:'',
        getById:'/',
        update:'/',
        delete:'/'
    },
    comment:{
        base:'/Comment',
        add:'',
        getAll:'',
        getById:'/',
        update:'/',
        delete:'/',
        getByTrackId:'/ByTrackId/'
    },
    experience:{
        base:'/Experience',
        add:'',
        getAll:'',
        getById:'/',
        update:'/',
        delete:'/'
    },
    dayPart:{
        base:'/DayPart',
        add:'',
        getAll:'',
        getById:'/',
        update:'/',
        delete:'/'
    },
    level:{
        base:'/Level',
        add:'',
        getAll:'',
        getById:'/',
        update:'/',
        delete:'/'
    },
    status:{
        base:'/Status',
        add:'',
        getAll:'',
        getById:'/',
        update:'/',
        delete:'/'
    },
    stop:{
        base:'/Stop',
        add:'',
        getAll:'',
        getById:'/',
        update:'/',
        delete:'/'
    },
    company:{
        base:'/Company',
        add:'',
        getAll:'',
        getById:'/',
        update:'/',
        delete:'/'
    },
    track:{
        base:'/Track',
        add:'',
        getAll:'',
        getById:'/',
        update:'/',
        delete:'/',
        getTracksByOption:'/TracksByOption/',
        getMyTracks:'/MyTracks/',
        getTracksByArea:'/TracksByArea/',
        getTracksByText:'/TracksByText/',
        getTrackPicture:'/picture/'
    },
    user:{
        base:'/User',
        add:'',
        getAll:'',
        getById:'/',
        update:'/',
        delete:'/',
        getUserByToken:'/UserByToken',
        getUserPicture:'/picture/',
        addFavorite:'/AddFavorite/',
        deleteFavorite:'/DeleteFavorite/',
        login:'/Login/'
    },
    view:{
        base:'/View',
        add:'',
        getAll:'',
        getById:'/',
        update:'/',
        delete:'/'
    }
}
export const baseUrl={
    url:'https://localhost:7090/api'
}